### PR TITLE
Generate dpkg.yaml for OSS compliance

### PR DESCRIPTION
**Pull request by ilasc**
I'm not actually able to build this snap as I was for core, core18 or core20.
I'm getting a multipass error: " launch failed: Unable to find an image matching "core22". An error occurred with the instance when trying to launch with 'multipass': returned exit code 2. Ensure that 'multipass' is setup correctly and try again."
I'm using snapcraft version 5.0 and multipass  1.7.1.
It would be ideal if I could build locally to see if the list of packages in the unit test is  correct for core22.

### CODE REVIEW

**Comment by stulluk** [comment]
> I'm not actually able to build this snap as I was for core, core18 or core20.
> I'm getting a multipass error: " launch failed: Unable to find an image matching "core22". An error occurred with the instance when trying to launch with 'multipass': returned exit code 2. Ensure that 'multipass' is setup correctly and try again."
> I'm using snapcraft version 5.0 and multipass  1.7.1.
> It would be ideal if I could build locally to see if the list of packages in the unit test is  correct for core22.

Hi, thank you very much for your great work !

You are getting that error because "core22" keyword is not yet known by Multipass or LXD backends from snapcraft. We are working on it, hope that will be landed before 22.04 release.

I managed to build this repository as follows: https://pastebin.ubuntu.com/p/26Bvb56YWx/

Please let me know if that works for you @ilasc

**Comment by ilasc** [comment]
@stulluk Thank you for the update!
With the approach you've shared, it does indeed build from master for me too.
However, as soon as I switch from master to any other branch, or make edits on master the initial build fails with: https://pastebin.canonical.com/p/TfGb6qJ4MB/

**Comment by stulluk** [comment]
> @stulluk Thank you for the update!
> With the approach you've shared, it does indeed build from master for me too.
> However, as soon as I switch from master to any other branch, or make edits on master the initial build fails with: https://pastebin.canonical.com/p/TfGb6qJ4MB/

Can you try again with "snapcraft clean --destructive-mode" first , and then "snapcraft --destructive-mode" ?

**Comment by ilasc** [comment]
@stulluk thank you for the prompt responses and your help on this ! 
I can now build the snap successfully and the generated yaml file for core22 has the following content: https://pastebin.canonical.com/p/6WPbV5JrSC/ 
One interesting thing I found was: a previous test that I didn't touch for this PR (hook-tests/001-extra-packages.test) was not passing for me locally unless I removed "libffi8ubuntu1:amd64" from the package list in that test.
This PR is now ready for review.

**Review by stulluk — APPROVED** [review]
LGTM, thanks. @ilasc are there any changes that are applied to core20 repo but not available in this PR yet ? If not, approving, thanks. @alfonsosanchezbeato fyi.

**Review by alfonsosanchezbeato — APPROVED** [review]
LGTM, merging after checking with @ilasc

**Pull request merged**
